### ISSUE TITLE
some default armor recipes still in game

### ISSUE THREAD

**Issue by theuberpony** [nbarber20/MyCraft#3]
![Annotation 2019-07-18 220916](https://user-images.githubusercontent.com/53067847/61505124-bbfe0780-a9ab-11e9-9ece-4707c4ac6861.jpg)
![Annotation 2019-07-18 224115](https://user-images.githubusercontent.com/53067847/61505573-4b57ea80-a9ad-11e9-8690-80324bb09b8e.jpg)
![Annotation 2019-07-18 224131](https://user-images.githubusercontent.com/53067847/61505575-4e52db00-a9ad-11e9-9a7b-690de51945ce.jpg)

this was in REI, but I deleted all mods but this one and the recipes were still there. it's not a big deal but I figured I would bring it to your attention. /shrug

**Comment by Nathan22211** [comment]
in my case iv'e noticed it too when developing my content pack. the only fix i can see on my end is replaceing both mycraft and minecraft's recipes with my own json's

**Comment by nbarber20** [comment]
should be fixed in 1.2.4
